[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-entities"
version = "0.9.1"

[dependencies]

chrono = { version = "0.4", default-features = false, features = ["serde"] }
poem-openapi = { version = "5.0", features = ["chrono", "uuid"] }
sea-orm = { version = "0.12.15", features = [
    "macros",
    "with-chrono",
    "with-uuid",
    "with-json",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
uuid = { version = "1.8", features = ["v4", "serde"] }
warpgate-common = { version = "*", path = "../warpgate-common" }

[features]
offline = []
migrate = []
_tls-native-tls = []
