[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-protocol-mysql"
version = "0.9.1"

[dependencies]
anyhow = { version = "1.0", features = ["std"] }
async-trait = "0.1"
bytes = "1.6"
futures = "0.3"
mysql_common = "0.32"
once_cell = "1.19"
password-hash = { version = "0.5", features = ["std"] }
rand = "0.8"
#rustls = { version = "0.21.12", features = ["dangerous_configuration"] }
rustls-native-certs = "0.7"
rustls-pemfile = "2.1"
sha1 = "0.10.6"
stream-reconnect = "0.3"
thiserror = "1.0"
tokio = { version = "1.38", features = ["full"] }
tokio-rustls = { version = "0.26", features = ["dangerous_configuration"] }
tokio-tungstenite = "0.23"
tracing = "0.1"
uuid = { version = "1.8", features = ["v4"] }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-core = { version = "*", path = "../warpgate-core" }
warpgate-database-protocols = { version = "*", path = "../warpgate-database-protocols" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
webpki = "0.22"
webpki-roots = "0.26"
