[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-admin"
version = "0.9.1"

[dependencies]
anyhow = { version = "1.0", features = ["std"] }
async-trait = "0.1"
bytes = "1.6"
chrono = { version = "0.4", default-features = false }
futures = "0.3"
hex = "0.4"
mime_guess = { version = "2.0", default-features = false }
poem = { version = "3.0.1", features = [
    "cookie",
    "session",
    "anyhow",
    "websocket",
] }
poem-openapi = { version = "5.0", features = [
    "swagger-ui",
    "chrono",
    "uuid",
    "static-files",
] }
russh-keys = { version = "0.43.0", features = ["openssl"] }
# russh-keys = { version = "0.43.0", features = [ "openssl",], path = "../../russh/russh-keys" }
rust-embed = "8.4"
sea-orm = { version = "0.12.15", features = [
    "runtime-tokio-native-tls",
    "macros",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.38", features = ["tracing"] }
tracing = "0.1"
uuid = { version = "1.8", features = ["v4", "serde"] }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-core = { version = "*", path = "../warpgate-core" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-protocol-ssh = { version = "*", path = "../warpgate-protocol-ssh" }
regex = "1.10"
