[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-migrations"
publish = false
version = "0.11.0"

[lib]

[dependencies]
async-std = { version = "^1.13", features = ["attributes"] }
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
sea-orm = { version = "1.0", features = [
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
    "with-uuid",
    "with-json",
], default-features = false }
sea-orm-migration = { version = "1.0", default-features = false, features = [
    "cli",
] }
uuid = { version = "1.3", features = ["v4", "serde"] }
serde_json = "1.0"

[features]
postgres = ["sea-orm/sqlx-postgres"]
mysql = ["sea-orm/sqlx-mysql"]
sqlite = ["sea-orm/sqlx-sqlite"]
