name: Test

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        with:
          key: "test"

      - name: Install build deps
        run: |
          sudo apt-get install openssh-client expect
          cargo install just
          cargo install cargo-llvm-cov
          cargo clean
          rustup component add llvm-tools-preview

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build admin UI
        run: |
          just yarn --network-timeout 1000000000
          just openapi
          just yarn build

      - name: Build images
        working-directory: tests
        run: |
          make all

      - name: Install deps
        working-directory: tests
        run: |
          sudo apt install -y gnome-keyring
          rm -rf poetry.lock
          pip3 install keyring==23.8.2 poetry==1.1.14
          poetry lock
          poetry install

      - name: Run
        working-directory: tests
        run: |
          TIMEOUT=120 poetry run ./run.sh
          cargo llvm-cov --no-run --hide-instantiations --lcov > coverage.lcov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: github.repository_owner == 'warp-tech' && github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
